service: auth-server

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  timeout: 30 # default is 6
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    PROJECT_ID: ${file(config.json):PROJECT_ID}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}
functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: /api/get-auth-url
          method: get
          cors: true
  getAccessTokenURL:
    handler: handler.getAccessTokenURL
    events:
      - http:
          path: /api/token/{code}
          method: get
          cors: true
  getCalendarEventsURL:
    handler: handler.getCalendarEventsURL
    events:
      - http:
          path: /api/get-events/{access_token}
          method: get
          cors: true